version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "wildsebastian"
  - package-ecosystem: "npm"
    directory: "/Website/Frontend"
    schedule:
      interval: "weekly"
    reviewers:
      - "wildsebastian"
