volumes:
  pg_data:

services:
  website:
    image: website
    build:
      context: .
      dockerfile: Website/Dockerfile

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
       POSTGRES_USER: website
       POSTGRES_PASSWORD: website
       POSTGRES_DB: website
